apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    isDefault: true
    access: proxy
    database: sensors
    user: influx
    password: "influx"
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
